from django.apps import AppConfig


class InstitutionConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'institution'

    def ready(self):
        from .signals import send_institution_registration_email,send_admin_registration_email,send_institution_profile_update_email,send_admin_profile_update_notification,send_institution_settings_received_email,send_admin_settings_received_email,send_institution_settings_update_email,send_admin_settings_update_notification,send_student_registration_link,delete_institution,send_newsletter_signup_confirmation,send_issue_creation_email,send_issue_resolution_email,send_proof_under_review,send_proof_verified,send_proof_rejected,send_receipt,notify_admin_payment_verification,notify_admin_contactus_form,notify_admin_issue_reported